theme: jekyll-theme-slate
google_site_verification: D5ixU_08KXu4tDMaycnskWkUtkC3kO5oKSb6NTsfXPE

favicon: ./assets/images/rainfighters-192x192-dark-sphere.png
logo: ./assets/images/rainfighters-512x512-dark-sphere.png

plugins:
  - jekyll-seo-tag

markdown: kramdown

kramdown:
  syntax_highlighter: rouge
  input: GFM
  toc_levels: 2..6

defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/rain-fighters-preview-920x920.png
