theme: jekyll-theme-slate
google_site_verification: D5ixU_08KXu4tDMaycnskWkUtkC3kO5oKSb6NTsfXPE

gems:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-seo-tag
 
defaults:
  - scope:
	  path: ""
	values:
	  image: /assets/images/rain-fighters-preview-940x940.png
